# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170117_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='album_id',
        ),
    ]
